# Update this with your Supabase project ID
project_id = "your-project-id"

[functions.recover-edit-link]
verify_jwt = false

[functions.event-calendar]
verify_jwt = false

[functions.create-event]
verify_jwt = false

[functions.notify-rsvp]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.notify-waitlist-promotion]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.event-share]
verify_jwt = false